/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_jni_JniClient */

#ifndef _Included_com_example_testndk_jni_JniClient
#define _Included_com_example_testndk_jni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndk_jni_JniClient
 * Method:    AddStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testndk_jni_JniClient_AddStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_testndk_jni_JniClient
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testndk_jni_JniClient_addInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
